export const images = {
    cards: {
        '15co' : require('../assets/Images/cards/2co.png'),
        '15ro' : require('../assets/Images/cards/2ro.png'),
        '15chuon' : require('../assets/Images/cards/2chuon.png'),
        '15bich' : require('../assets/Images/cards/2bich.png'),
        '3co' : require('../assets/Images/cards/3co.png'),
        '3ro' : require('../assets/Images/cards/3ro.png'),
        '3chuon' : require('../assets/Images/cards/3chuon.png'),
        '3bich' : require('../assets/Images/cards/3bich.png'),
        '4co' : require('../assets/Images/cards/4co.png'),
        '4ro' : require('../assets/Images/cards/4ro.png'),
        '4chuon' : require('../assets/Images/cards/4chuon.png'),
        '4bich' : require('../assets/Images/cards/4bich.png'),
        '5co' : require('../assets/Images/cards/5co.png'),
        '5ro' : require('../assets/Images/cards/5ro.png'),
        '5chuon' : require('../assets/Images/cards/5chuon.png'),
        '5bich' : require('../assets/Images/cards/5bich.png'),
        '6co' : require('../assets/Images/cards/6co.png'),
        '6ro' : require('../assets/Images/cards/6ro.png'),
        '6chuon' : require('../assets/Images/cards/6chuon.png'),
        '6bich' : require('../assets/Images/cards/6bich.png'),
        '7co' : require('../assets/Images/cards/7co.png'),
        '7ro' : require('../assets/Images/cards/7ro.png'),
        '7chuon' : require('../assets/Images/cards/7chuon.png'),
        '7bich' : require('../assets/Images/cards/7bich.png'),
        '8co' : require('../assets/Images/cards/8co.png'),
        '8ro' : require('../assets/Images/cards/8ro.png'),
        '8chuon' : require('../assets/Images/cards/8chuon.png'),
        '8bich' : require('../assets/Images/cards/8bich.png'),
        '9co' : require('../assets/Images/cards/9co.png'),
        '9ro' : require('../assets/Images/cards/9ro.png'),
        '9chuon' : require('../assets/Images/cards/9chuon.png'),
        '9bich' : require('../assets/Images/cards/9bich.png'),
        '10co' : require('../assets/Images/cards/10co.png'),
        '10ro' : require('../assets/Images/cards/10ro.png'),
        '10chuon' : require('../assets/Images/cards/10chuon.png'),
        '10bich' : require('../assets/Images/cards/10bich.png'),
        '11co' : require('../assets/Images/cards/jco.png'),
        '11ro' : require('../assets/Images/cards/jro.png'),
        '11chuon' : require('../assets/Images/cards/jchuon.png'),
        '11bich' : require('../assets/Images/cards/jbich.png'),
        '12co' : require('../assets/Images/cards/qco.png'),
        '12ro' : require('../assets/Images/cards/qro.png'),
        '12chuon' : require('../assets/Images/cards/qchuon.png'),
        '12bich' : require('../assets/Images/cards/qbich.png'),
        '13co' : require('../assets/Images/cards/kco.png'),
        '13ro' : require('../assets/Images/cards/kro.png'),
        '13chuon' : require('../assets/Images/cards/kchuon.png'),
        '13bich' : require('../assets/Images/cards/kbich.png'),
        '14co' : require('../assets/Images/cards/aco.png'),
        '14ro' : require('../assets/Images/cards/aro.png'),
        '14chuon' : require('../assets/Images/cards/achuon.png'),
        '14bich' : require('../assets/Images/cards/abich.png'),
    },
    users: {
        '1': require('../assets/Images/user/1.png'),
        '2': require('../assets/Images/user/2.png'),
        '3': require('../assets/Images/user/3.png'),
        '4': require('../assets/Images/user/4.png'),
        '5': require('../assets/Images/user/5.png'),
        '6': require('../assets/Images/user/6.png'),
        '7': require('../assets/Images/user/7.png'),
        '8': require('../assets/Images/user/8.png'),
        '9': require('../assets/Images/user/9.png'),
        '10': require('../assets/Images/user/10.png'),
        '11': require('../assets/Images/user/11.png'),
        '12': require('../assets/Images/user/12.png'),
        '13': require('../assets/Images/user/13.png'),
        '14': require('../assets/Images/user/14.png'),
        '15': require('../assets/Images/user/15.png'),
        '16': require('../assets/Images/user/16.png'),
        '17': require('../assets/Images/user/17.png'),
        '18': require('../assets/Images/user/18.png'),
        '19': require('../assets/Images/user/19.png'),
        '20': require('../assets/Images/user/20.png'),
        '21': require('../assets/Images/user/21.png'),
        '22': require('../assets/Images/user/22.png'),
        '23': require('../assets/Images/user/23.png'),
        '24': require('../assets/Images/user/24.png'),
        '25': require('../assets/Images/user/25.png'),
        '26': require('../assets/Images/user/26.png'),
        '27': require('../assets/Images/user/27.png'),
        '28': require('../assets/Images/user/28.png'),
        '29': require('../assets/Images/user/29.png'),
        '30': require('../assets/Images/user/30.png'),
        '31': require('../assets/Images/user/31.png'),
        '32': require('../assets/Images/user/32.png'),
        '33': require('../assets/Images/user/33.png'),
        '34': require('../assets/Images/user/34.png'),
        '35': require('../assets/Images/user/35.png'),
        '36': require('../assets/Images/user/36.png'),
        '37': require('../assets/Images/user/37.png'),
        '38': require('../assets/Images/user/38.png'),
        '39': require('../assets/Images/user/39.png'),
        '40': require('../assets/Images/user/40.png'),
        '41': require('../assets/Images/user/41.png'),
        '42': require('../assets/Images/user/42.png'),
        '43': require('../assets/Images/user/43.png'),
        '44': require('../assets/Images/user/44.png'),
        '45': require('../assets/Images/user/45.png'),
        '46': require('../assets/Images/user/46.png'),
        '47': require('../assets/Images/user/47.png'),
        '48': require('../assets/Images/user/48.png'),
        '49': require('../assets/Images/user/49.png'),
        '50': require('../assets/Images/user/50.png'),
        '51': require('../assets/Images/user/51.png'),
        '52': require('../assets/Images/user/52.png'),
        '53': require('../assets/Images/user/53.png'),
        '54': require('../assets/Images/user/54.png'),
    },
    numberssub: {
        '1': require('../assets/Images/numberssub/1.png'),
        '0': require('../assets/Images/numberssub/0.png'),
        '2': require('../assets/Images/numberssub/2.png'),
        '3': require('../assets/Images/numberssub/3.png'),
        '4': require('../assets/Images/numberssub/4.png'),
        '5': require('../assets/Images/numberssub/5.png'),
        '6': require('../assets/Images/numberssub/6.png'),
        '7': require('../assets/Images/numberssub/7.png'),
        '8': require('../assets/Images/numberssub/8.png'),
        '9': require('../assets/Images/numberssub/9.png'),
        'sub': require('../assets/Images/numberssub/sub.png')
    },
    numbersadd: {
        '1': require('../assets/Images/numbersadd/1.png'),
        '0': require('../assets/Images/numbersadd/0.png'),
        '2': require('../assets/Images/numbersadd/2.png'),
        '3': require('../assets/Images/numbersadd/3.png'),
        '4': require('../assets/Images/numbersadd/4.png'),
        '5': require('../assets/Images/numbersadd/5.png'),
        '6': require('../assets/Images/numbersadd/6.png'),
        '7': require('../assets/Images/numbersadd/7.png'),
        '8': require('../assets/Images/numbersadd/8.png'),
        '9': require('../assets/Images/numbersadd/9.png'),
        'add': require('../assets/Images/numbersadd/add.png')
    }
}